# Generated by Django 4.1.4 on 2023-11-29 18:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('imagen_de_fondo', models.ImageField(blank=True, null=True, upload_to='background_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asbesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_asbesto', models.ImageField(blank=True, null=True, upload_to='asbesto/')),
                ('titulo_asbesto', models.CharField(max_length=200)),
                ('fecha_asbesto', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_asbesto', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_condominio', models.ImageField(blank=True, null=True, upload_to='condominio/')),
                ('titulo_condominio', models.CharField(max_length=200)),
                ('fecha_condominio', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_condominio', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
            ],
        ),
        migrations.CreateModel(
            name='Energetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_energetico', models.ImageField(blank=True, null=True, upload_to='energetico/')),
                ('titulo_energetico', models.CharField(max_length=200)),
                ('fecha_energetico', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_energetico', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_reconstruccion', models.ImageField(blank=True, null=True, upload_to='reconstruccion/')),
                ('titulo_reconstruccion', models.CharField(max_length=200)),
                ('fecha_reconstruccion', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_reconstruccion', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_social', models.ImageField(blank=True, null=True, upload_to='social/')),
                ('titulo_social', models.CharField(max_length=200)),
                ('fecha_social', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_social', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Verdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_verdes', models.ImageField(blank=True, null=True, upload_to='verdes/')),
                ('titulo_verdes', models.CharField(max_length=200)),
                ('fecha_verdes', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_verdes', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_vivienda', models.ImageField(blank=True, null=True, upload_to='vivienda/')),
                ('titulo_vivienda', models.CharField(max_length=200)),
                ('fecha_vivienda', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_vivienda', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes3/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='Verdes_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('verdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.verdes')),
            ],
        ),
        migrations.CreateModel(
            name='Verdes_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('verdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.verdes')),
            ],
        ),
        migrations.CreateModel(
            name='Verdes_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('verdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.verdes')),
            ],
        ),
        migrations.CreateModel(
            name='Verdes_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes5/')),
                ('verdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.verdes')),
            ],
        ),
        migrations.CreateModel(
            name='Social_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.social')),
            ],
        ),
        migrations.CreateModel(
            name='Social_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.social')),
            ],
        ),
        migrations.CreateModel(
            name='Social_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.social')),
            ],
        ),
        migrations.CreateModel(
            name='Social_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes1/')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.social')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruccion_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('reconstruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.reconstruccion')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruccion_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('reconstruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.reconstruccion')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruccion_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('reconstruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.reconstruccion')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruccion_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes4/')),
                ('reconstruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.reconstruccion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Energetico_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('energetico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.energetico')),
            ],
        ),
        migrations.CreateModel(
            name='Energetico_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('energetico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.energetico')),
            ],
        ),
        migrations.CreateModel(
            name='Energetico_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('energetico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.energetico')),
            ],
        ),
        migrations.CreateModel(
            name='Energetico_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes2/')),
                ('energetico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.energetico')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes6/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='principal.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Asbesto_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('asbesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.asbesto')),
            ],
        ),
        migrations.CreateModel(
            name='Asbesto_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('asbesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.asbesto')),
            ],
        ),
        migrations.CreateModel(
            name='Asbesto_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('asbesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.asbesto')),
            ],
        ),
        migrations.CreateModel(
            name='Asbesto_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes7/')),
                ('asbesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.asbesto')),
            ],
        ),
    ]
