# Generated by Django 4.1.4 on 2023-12-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_comunitaria', models.ImageField(blank=True, null=True, upload_to='comunitaria/')),
                ('titulo_comunitaria', models.CharField(max_length=200)),
                ('fecha_comunitaria', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
                ('texto_comunitaria', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
            ],
        ),
        migrations.CreateModel(
            name='Comunitaria_imagen4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('comunitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes4', to='principal.comunitaria')),
            ],
        ),
        migrations.CreateModel(
            name='Comunitaria_imagen3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('comunitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes3', to='principal.comunitaria')),
            ],
        ),
        migrations.CreateModel(
            name='Comunitaria_imagen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('comunitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes2', to='principal.comunitaria')),
            ],
        ),
        migrations.CreateModel(
            name='Comunitaria_imagen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes8/')),
                ('comunitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes1', to='principal.comunitaria')),
            ],
        ),
    ]
